version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  relative-path-mode: gomod
  go: "1.25.0"

linters:
  default: standard
  enable:
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
